// Modal Icons - همه آیکون‌ها با رنگ‌های اصلی

// Contact icons
export { default as telegram } from './contact/telegram.vue'
export { default as email } from './contact/email.vue'
export { default as number } from './contact/number.vue'
export { default as call } from './contact/call.vue'
export { default as contactcard } from './contact/contactcard.vue'
export { default as address } from './contact/address.vue'
export { default as facetime } from './contact/facetime.vue'
export { default as whatsapp } from './contact/whatsapp.vue'
export { default as eitaa } from './contact/eitaa.vue'
export { default as linkumap } from './contact/map.vue'

// Social Media icons
export { default as instagram } from './SocialMedia/instagram.vue'
export { default as facebook } from './SocialMedia/facebook.vue'
export { default as tiktok } from './SocialMedia/tiktok.vue'
export { default as x } from './SocialMedia/x.vue'
export { default as linkedin } from './SocialMedia/linkedin.vue'
export { default as youtube } from './SocialMedia/youtube.vue'
export { default as aparat } from './SocialMedia/aparat.vue'
export { default as discord } from './SocialMedia/discord.vue'
export { default as snapchat } from './SocialMedia/snapchat.vue'
export { default as pinterest } from './SocialMedia/pinterest.vue'
export { default as threads } from './SocialMedia/threads.vue'
export { default as twitch } from './SocialMedia/twitch.vue'
export { default as clubhouse } from './SocialMedia/clubhouse.vue'
export { default as bale } from './SocialMedia/bale.vue'
export { default as rubika } from './SocialMedia/rubika.vue'
export { default as igap } from './SocialMedia/igap.vue'
export { default as medium } from './SocialMedia/medium.vue'
export { default as virgool } from './SocialMedia/virgool.vue'

// Business icons
export { default as website } from './Business/website.vue'
export { default as calendly } from './Business/calendly.vue'
export { default as googlemeet } from './Business/googlemeet.vue'
export { default as zoom } from './Business/zoom.vue'
export { default as teams } from './Business/teams.vue'
export { default as github } from './Business/github.vue'
export { default as figma } from './Business/figma.vue'
export { default as app_link } from './Business/app_link.vue'
export { default as balad } from './Business/balad.vue'
export { default as nshan } from './Business/nshan.vue'
export { default as reviews } from './Business/reviews.vue'
export { default as trustpilot } from './Business/trustpilot.vue'
export { default as microsoft_bookings } from './Business/microsoft_bookings.vue'
export { default as clock } from './Business/clock.vue'
export { default as card } from './Business/card.vue'
export { default as divar } from './Business/divar.vue'
export { default as snapp } from './Business/snapp.vue'
export { default as booksy } from './Business/booksy.vue'
export { default as etsy } from './Business/etsy.vue'
export { default as yelp } from './Business/yelp.vue'
export { default as zillow } from './Business/zillow.vue'
export { default as square } from './Business/square.vue'
export { default as chili } from './Business/chili.vue'
export { default as map } from './Business/linkumap.vue'

// Payment icons
export { default as zarinpal } from './Payment/zarinpal.vue'
export { default as paypal } from './Payment/paypal.vue'
export { default as cashapp } from './Payment/cashapp.vue'
export { default as remit } from './Payment/remit.vue'
export { default as trustwallet } from './Payment/trustwallet.vue'
export { default as zelle } from './Payment/zelle.vue'

// Content icons
export { default as customlink } from './Content/customlink.vue'
export { default as basiclink } from './Content/customlink.vue'
export { default as embeddedvideo } from './Content/embeddedvideo.vue'
export { default as featured } from './Content/featured.vue'
export { default as featuredlink } from './Content/featured.vue'
export { default as file } from './Content/file.vue'
export { default as poll } from './Content/poll.vue'
export { default as questionbox } from './Content/questionbox.vue'
export { default as textsection } from './Content/textSection.vue'
export { default as expandabletext } from './Content/textSection.vue'
export { default as dropdown } from './Content/dropDown.vue'

// Club icons
export { default as luckyegg } from './Club/luckyegg.vue'
export { default as luckydice } from './Club/luckydice.vue'
export { default as luckywheel } from './Club/luckywheel.vue'
export { default as form } from './Club/form.vue'
export { default as builder } from './Club/form.vue'

// Music icons
export { default as spotify } from './Music/spotify.vue'
export { default as soundcloud } from './Music/soundcloud.vue'
export { default as apple_music } from './Music/apple_music.vue'
export { default as youtube_music } from './Music/youtube_music.vue'
export { default as podcasts } from './Music/podcasts.vue'
export { default as linktree } from './Music/linktree.vue'
export { default as poshmark } from './Music/poshmark.vue'
export { default as opensea } from './Music/opensea_color.vue'
export { default as hoobe } from './Music/hoobe.vue'